/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.regexp.JoniRegExp;
import logica.Data;
import modelos.Paciente;
import util.utilidades;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Administrador
 */
public class frmPaciente extends javax.swing.JFrame {
     private static Data mc = new Data();
        String sexoseleccionado="";
        String estadoseleccionado="";
    /**
     * Creates new form Paciente
     */
    public frmPaciente() {
        initComponents();
        cargarpacientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        estado = new javax.swing.ButtonGroup();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtnombre = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtid = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtapellido = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtedad = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtdireccion = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtcorreo = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txttelefono = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        txttiposangre = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtfecha = new javax.swing.JTextPane();
        RBMasculino = new javax.swing.JRadioButton();
        RBFemefino = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        RBSActivo = new javax.swing.JRadioButton();
        RBSInactivo = new javax.swing.JRadioButton();
        btnnuevo = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("INGRESAR PACIENTE");

        jLabel2.setText("NOMBRE *");

        jLabel3.setText("APELLIDO *");

        jLabel4.setText("EDAD *");

        jLabel5.setText("TIPO SANGUINEO *");

        jLabel6.setText("DIRECCION");

        jLabel7.setText("IDENTIFICACION *");

        jLabel8.setText("TELEFONO");

        jLabel9.setText("CORREO *");

        jScrollPane1.setViewportView(txtnombre);

        jScrollPane2.setViewportView(txtid);

        jScrollPane3.setViewportView(txtapellido);

        jScrollPane4.setViewportView(txtedad);

        jScrollPane5.setViewportView(txtdireccion);

        jScrollPane6.setViewportView(txtcorreo);

        jScrollPane7.setViewportView(txttelefono);

        jScrollPane9.setViewportView(txttiposangre);

        jButton1.setText("Reporte Citas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Citas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setText("ESTADO *");

        jLabel11.setText("FECHA NACIMIENTO *");

        jScrollPane8.setViewportView(txtfecha);

        sexo.add(RBMasculino);
        RBMasculino.setText("Masculino");
        RBMasculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RBMasculinoMouseClicked(evt);
            }
        });

        sexo.add(RBFemefino);
        RBFemefino.setText("Femenino");
        RBFemefino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RBFemefinoMouseClicked(evt);
            }
        });

        jLabel12.setText("GËNERO *");

        estado.add(RBSActivo);
        RBSActivo.setText("Activo");
        RBSActivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RBSActivoMouseClicked(evt);
            }
        });

        estado.add(RBSInactivo);
        RBSInactivo.setText("Inactivo");
        RBSInactivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RBSInactivoMouseClicked(evt);
            }
        });

        btnnuevo.setText("Nuevo ");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar ");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(61, 61, 61)
                                .addComponent(jScrollPane6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane7)
                                            .addComponent(jScrollPane4)
                                            .addComponent(jScrollPane5)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3))
                                                .addGap(36, 36, 36)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane2))))))
                                .addGap(2, 2, 2)))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RBMasculino)
                                .addGap(18, 18, 18)
                                .addComponent(RBFemefino))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(52, 52, 52))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RBSActivo)
                                        .addGap(18, 18, 18)
                                        .addComponent(RBSInactivo))
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnconsultar)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnactualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBMasculino)
                            .addComponent(RBFemefino))
                        .addGap(45, 45, 45)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBSActivo)
                            .addComponent(RBSInactivo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnnuevo)
                    .addComponent(btnconsultar)
                    .addComponent(btnactualizar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
       
        if(!validarcampos()){
            JOptionPane.showMessageDialog(rootPane, "Los campos marcados con (*) son obligatorios","Campos vacios",JOptionPane.ERROR_MESSAGE);
        }else
        if(sexoseleccionado.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Debe selecionar un género","Seleccione genero",JOptionPane.ERROR_MESSAGE);
        }else
        if(estadoseleccionado.equals("")){
        JOptionPane.showMessageDialog(rootPane, "Debe selecionar un estado","Seleccione estado",JOptionPane.ERROR_MESSAGE);
        
        }else
                    if(!utilidades.checkEmail(txtcorreo.getText())){
                        JOptionPane.showMessageDialog(rootPane, "Debe ingresar un email válido, ej: example@dominio.com.","Error correo",JOptionPane.ERROR_MESSAGE);
                        
                    }
        
        else{
            try {
                Paciente paciente=new Paciente();
                paciente.id=txtid.getText();
                paciente.name=txtnombre.getText();
                paciente.lastname=txtapellido.getText();
                paciente.birthdate=txtfecha.getText();
                paciente.age=txtedad.getText();
                paciente.gender=sexoseleccionado;
                paciente.address=txtdireccion.getText();
                paciente.phone=txttelefono.getText();
                paciente.email=txtcorreo.getText();
                paciente.bloodtype=txttiposangre.getText();
                paciente.state=estadoseleccionado;
                mc.NuevoPaciente(paciente);
                JOptionPane.showMessageDialog(rootPane, "Registro ingresado correctamente.!","Confirmación",JOptionPane.INFORMATION_MESSAGE);
               limpiarcampos();
                 cargarpacientes();
            } catch (SQLException ex) {
                Logger.getLogger(frmPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void RBMasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBMasculinoMouseClicked
        validargenero(RBMasculino.getLabel());
        
    }//GEN-LAST:event_RBMasculinoMouseClicked

    private void RBFemefinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBFemefinoMouseClicked
       
        validargenero(RBFemefino.getLabel());
    }//GEN-LAST:event_RBFemefinoMouseClicked

    private void RBSActivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBSActivoMouseClicked
        validarestado(RBSActivo.getLabel());
        
    }//GEN-LAST:event_RBSActivoMouseClicked

    private void RBSInactivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBSInactivoMouseClicked
        validarestado(RBSInactivo.getLabel());
    }//GEN-LAST:event_RBSInactivoMouseClicked

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
         try {
             if(txtid.getText().equals("")){
                 JOptionPane.showMessageDialog(rootPane, "Ingrese un Id de paciente para consultar","Información",JOptionPane.ERROR_MESSAGE);
             
             }else{
             Paciente paciente=mc.GetPaciente(txtid.getText().trim());
                    
             txtid.setText(paciente.id);
             txtnombre.setText(paciente.name);
             txtapellido.setText(paciente.lastname);
             txtfecha.setText(paciente.birthdate);
             txtedad.setText(paciente.age);
             txtdireccion.setText(paciente.address);
             txttelefono.setText(paciente.phone);
             txtcorreo.setText(paciente.email);
             txttiposangre.setText(paciente.bloodtype);
            
             if(paciente.gender.equals(RBMasculino.getLabel())){
             RBMasculino.setSelected(true);
             }else if(paciente.gender.equals(RBFemefino.getLabel())){
             RBFemefino.setSelected(true);
             }
             if(paciente.state.equals(RBSActivo.getLabel())){
             RBSActivo.setSelected(true);
             }else if(paciente.state.equals(RBSInactivo.getLabel())){
             RBSInactivo.setSelected(true);
            
                 validargenero(paciente.gender);
                 validarestado(paciente.state);
            
             }
              
             }
            
         } catch (SQLException ex) {
             Logger.getLogger(frmPaciente.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        
      
        if(!validarcampos()){
            JOptionPane.showMessageDialog(rootPane, "Los campos marcados con (*) son obligatorios","Campos vacios",JOptionPane.ERROR_MESSAGE);
        }else
        if(sexoseleccionado.isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "Debe selecionar un género","Seleccione genero",JOptionPane.ERROR_MESSAGE);
        }else
        if(estadoseleccionado.isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "Debe selecionar un estado","Seleccione estado",JOptionPane.ERROR_MESSAGE);
        
        }else
                    if(!utilidades.checkEmail(txtcorreo.getText())){
                        JOptionPane.showMessageDialog(rootPane, "Debe ingresar un email válido, ej: example@dominio.com.","Error correo",JOptionPane.ERROR_MESSAGE);
                        
                    }
        
        else{
        
        try {
                Paciente paciente=new Paciente();
                paciente.id=txtid.getText();
                paciente.name=txtnombre.getText();
                paciente.lastname=txtapellido.getText();
                paciente.birthdate=txtfecha.getText();
                paciente.age=txtedad.getText();
                paciente.gender=sexoseleccionado;
                paciente.address=txtdireccion.getText();
                paciente.phone=txttelefono.getText();
                paciente.email=txtcorreo.getText();
                paciente.bloodtype=txttiposangre.getText();
                paciente.state=estadoseleccionado;
                mc.ActualizarPaciente(paciente);
                JOptionPane.showMessageDialog(rootPane, "Registro actualizado correctamente.!","Confirmación",JOptionPane.INFORMATION_MESSAGE);
               limpiarcampos();
                 cargarpacientes();
            } catch (SQLException ex) {
                Logger.getLogger(frmPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      if(txtid.getText().equals("")){
                 JOptionPane.showMessageDialog(rootPane, "Ingrese un Id de paciente para consultar","Información",JOptionPane.ERROR_MESSAGE);
             
             }else{
          try {
              mc.EliminarPaciente(txtid.getText());
            JOptionPane.showMessageDialog(rootPane, "Registro eliminado correctamente.!","Confirmación",JOptionPane.INFORMATION_MESSAGE);
                cargarpacientes();
          } catch (SQLException ex) {
              Logger.getLogger(frmPaciente.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String id=txtid.getText();
    String nombre=txtnombre.getText();
        if(id.isEmpty() ||nombre.isEmpty()){
                 JOptionPane.showMessageDialog(rootPane, "Debe consultar un paciente para agregar citas","Información",JOptionPane.ERROR_MESSAGE);
             
    }else{
        frmCitas fr=new frmCitas();
    fr.show();}   
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      frmReporCitas fr=new frmReporCitas();
      fr.show();
    }//GEN-LAST:event_jButton1ActionPerformed
private boolean validarcampos(){
if(txtid.getText().equals("") || txtnombre.getText().equals("") 
        ||txtapellido.getText().equals("")|| txtfecha.getText().equals("")
        || txtedad.getText().equals("")|| txtcorreo.getText().equals("")
        ||txttiposangre.getText().equals("")){
    return false;
}
return true;
}
private void validargenero(String sexo){
   sexoseleccionado=sexo;
   
}
private void validarestado(String estado){
estadoseleccionado=estado;
}
private void limpiarcampos(){
            txtid.setText("");
            txtnombre.setText("");
            txtapellido.setText("");
             txtfecha.setText("");
             txtedad.setText("");
             txtdireccion.setText("");
             txttelefono.setText("");
             txtcorreo.setText("");
             txttiposangre.setText("");
             
}
private void cargarpacientes(){
         try {
             ResultSet rs=mc.GetPacientes();
             jTable2.setModel(DbUtils.resultSetToTableModel(rs));
         } catch (SQLException ex) {
             Logger.getLogger(frmPaciente.class.getName()).log(Level.SEVERE, null, ex);
         }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBFemefino;
    private javax.swing.JRadioButton RBMasculino;
    private javax.swing.JRadioButton RBSActivo;
    private javax.swing.JRadioButton RBSInactivo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.ButtonGroup estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JTextPane txtapellido;
    private javax.swing.JTextPane txtcorreo;
    private javax.swing.JTextPane txtdireccion;
    private javax.swing.JTextPane txtedad;
    private javax.swing.JTextPane txtfecha;
    public static javax.swing.JTextPane txtid;
    public static javax.swing.JTextPane txtnombre;
    private javax.swing.JTextPane txttelefono;
    private javax.swing.JTextPane txttiposangre;
    // End of variables declaration//GEN-END:variables
}
